openapi: 3.1.0
info:
  version: 1.0.0
  title: My contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    Contacts app documentation
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Operations about auth.
servers:
  - url: http://localhost:3000
  # - url: #посилання на задеплоєний сайт
paths:
   /contacts: 
      get:
        $ref: ../swagger/paths/contacts/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
